#!/usr/bin/env bash
set -e
[ -n "${KOPSENV_DEBUG}" ] && set -x
source ${KOPSENV_ROOT}/libexec/helpers

if [ ${#} -ne 0 ];then
  echo "usage: kopsenv list-remote" 1>&2
  exit 1
fi

platform="$(kops_platform)"
(( "$?" )) && exit $?

# This is a bit hacky since it's relying on the formatting of URLs
# returned in JSON output from the github API, but there's no other
# reasonable way to get a list of the current kops versions using
# only curl + POSIX tools
json=$(curlw -s -L https://api.github.com/repos/kubernetes/kops/releases?per_page=100)
(( "$?" )) && exit $?

echo "$json" \
  | grep 'download/v\?[0-9\.]\{1,\}\(-[a-z]\{1,\}\.[0-9]\{1,\}\)\?/kops-'$platform'"' \
  | sed 's/^.*download\///; s/\/.*$//' \
  | sed 's/^v\?/\0,/' \
  | sort -t',' -k 2rV \
  | sed 's/^\(v\?\),/\1/' \
  | uniq

